[project]
name = "scoring-assistant"
version = "0.1.0"
description = "Yuta Endo"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "astyle-py>=1.0.5",
    "chardet>=5.2.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.4",
]
